# Generated by Django 2.1.2 on 2021-03-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='tweet',
            new_name='liked_to',
        ),
    ]
