# Generated by Django 3.1.7 on 2021-03-16 04:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0005_auto_20210316_0450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeOrDislike',
            new_name='Preference',
        ),
    ]
